# Torch 0.4.0
## torch.nn

### torch.Parameters
A kind of Tensor that is to be considered a module parameter.  

Parameters are Tensor subclasses, that have a very special property when used with Module s - when they’re assigned as Module attributes they are automatically added to the list of its parameters, and will appear e.g. in parameters() iterator. Assigning a Tensor doesn’t have such effect. This is because one might want to cache some temporary state, like last hidden state of the RNN, in the model. If there was no such class as Parameter, these temporaries would get registered too

**Parameters**：  
**data**: Tensor parameter tensor  
**requires_grad**:  Tensor bool optional

## Containers

### torch.nn.Module
Base class for all neural network modules  
Your models should also subclass this class.  
Modules can also contain other Modules, allowing to nest them in a tree structure. You can assign the submodules as regular attributes:

In [1]:
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.conv1 = nn.Conv2d(1,20,5)
        self.conv2 = nn.Conv2d(20,20,5)
    
    def forward(self,x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

#### add_module(name,module)
Adds a child module to the current module.  
The module can be accessed as an attribute using the given name.    
Parameters:	  
**name** (string) – name of the child module. The child module can be accessed from this module using the given name  
**parameter** (Module) – child module to be added to the module.

#### apply(fn)
applies fn recursively to every submodule (as returned by .children()) as well as self. Typical use includes initializing the parameters of a model (see also torch-nn-init).  
***Parameters***:  
**fn** (Module -> None) – function to be applied to each submodule  
***Returns***:  
self  

In [3]:
def init_weights(m):
    print(m)
    if type(m) == nn.Linear:
        m.weight.data.fill_(1.0)
        print(m.weight)

net = nn.Sequential(nn.Linear(2,2),nn.Linear(2,2))
net.apply(init_weights)

Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)


Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)

#### children()
Returns an iterator over immediate children modules.  

****
#### cpu()
Moves all model parameters and buffers to the cpu

****

#### cuda(device=None)
Moves all model parameters and buffers to the GPU.  
This also makes associated parameters and buffers different objects. So it should be called before constructing optimizer if the module will live on GPU while being optimized.  
***Parameters:***  
**device**: init optional -- if specified, all parameters will be copied to that device  
**Returns**: self (Module)

***

#### double()
casts all floating point parameters and buffers to double datatype

**Return** self

***

#### eval()
Sets the module in evaluation mode.  

This has any effect only on certain modules. See documentations of particular modules for details of their behaviors in training/evaluation mode, if they are affected, e.g. Dropout, BatchNorm, etc.
***
  
#### extra_repr()
Set the extra representation of the module  

To print customized extra information, you should reimplement this method in your own modules. Both single-line and multi-line strings are acceptable.  
***
#### float()
casts all floating  point parameters and buffers to float datatype  
**return**: self
***

#### forward(*input)
Defines the computation performed at every call.  
Should be overridden by all subclasses.  
***

#### half()
Casts all the floating poiny parameters and buffers to half datatype
**Return**: self

#### load_state_dict(state_dict,strict=True)
Copies parameters and buffers from state_dict into this module and its descendants. If strict is True, then the keys of state_dict must exactly match the keys returned by this module’s state_dict() function.  
***Parameters***:  
**state_dict**: a dict containing parameters and persistent buffers  
**strict**:(bool, optioanal) - whether to strictly enforce that the keys in state_dict match the keys returned by this module’s state_dict() function. Default: True  
***

#### modules()
Returns an iterator over all modules in the network  
*Note*: duplicate modules rae returned only once

In [6]:
l = nn.Linear(2,2)
net = nn.Sequential(l,l)
for idx,m in enumerate(net.modules()):
    print(idx,'->',m)

0 -> Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)
1 -> Linear(in_features=2, out_features=2, bias=True)


#### named_children()
Returns an iterator over immediate children modules, yielding both the name of the modules as well as the module itself  
**Yield**: (string,Module) - Tuple containing a name and child module  

In [14]:

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel,self).__init__()
        self.conv4 = nn.Conv2d(2,4,4)
        self.conv3 = nn.Conv2d(2,3,3)
        self.conv5 = nn.Conv2d(2,5,5)
model = MyModel()
for name,module in model.named_children():
    if name in ['conv4','conv5']:
        print(module)

Conv2d(2, 4, kernel_size=(4, 4), stride=(1, 1))
Conv2d(2, 5, kernel_size=(5, 5), stride=(1, 1))


#### named_modules(memo=None,prefix='')
Returns an iterator over all modules in the network, yielding both the name of the module as well as the module itself.  
**Yield**: (string,Module) - Tuple of name and module   
*Note*: duplicate modules rae returned only once

In [16]:
l = nn.Linear(2,2)
net = nn.Sequential(l,l,nn.Linear(3,3))
for idx,m in enumerate(net.named_modules()):
    print(idx,'->',m)

0 -> ('', Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
))
1 -> ('0', Linear(in_features=2, out_features=2, bias=True))
2 -> ('2', Linear(in_features=3, out_features=3, bias=True))


#### named_parameters(memo=None, prefix='')
Returns an iterator over module parameters.  
This is typically passed to an optimizer.  
**Yields**: *Parameter*-module parameter  
Maybe for 0.4.1, does not work under 0.4.0

In [ ]:
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel,self).__init__()
        self.conv4 = nn.Conv2d(2,4,4)
        self.conv3 = nn.Conv2d(2,3,3)
        self.conv5 = nn.Conv2d(2,5,5)
    def forward(self):
        for param in self.named_paramters():
            if name in ['bias']:
                print(param.size())
a = MyModel()
a()

#### parameters()  
Returns an iterator over module parameters.  
This is typically passed to an optimizer.  
**Yields**:	*Parameter* – module parameter  

In [24]:
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        self.conv1 = nn.Conv2d(1,20,5)
        self.conv2 = nn.Conv2d(20,20,5)
    
    def forward(self,x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))
model = Model()
for param in model.parameters():
    print(type(param.data),param.size())

<class 'torch.Tensor'> torch.Size([20, 1, 5, 5])
<class 'torch.Tensor'> torch.Size([20])
<class 'torch.Tensor'> torch.Size([20, 20, 5, 5])
<class 'torch.Tensor'> torch.Size([20])


#### register_backward_hook(hook):
Registers a backward hook on the module.  

The hook will be called every time the gradients with respect to module inputs are computed. The hook should have the following signature:  
>`hook(module, grad_input,grad_output) -> Tensor or None`

  
 The grad_input and grad_output may be tuples if the module has multiple inputs or outputs. The hook should not modify its arguments, but it can optionally return a new gradient with respect to input that will be used in place of grad_input in subsequent computations.  
**Returns**:	a handle that can be used to remove the added hook by calling handle.remove()  
**Return type**:	torch.utils.hooks.RemovableHandle

***
#### register_forward_hook(hook)
Registers a forward hook on the module.  
The hook will be called every time after `forward()` has computed an output.   
It should have the following signature:   
>`hook(module, input, output) -> None`   

The hook should not modify the input or output.  
**Returns**:	a handle that can be used to remove the added hook by calling `handle.remove()`  
**Return type**:	torch.utils.hooks.RemovableHandle

***
#### register_forward_pre_hook(hook)
Registers a forward pre-hook on the module.  
The hook will be called every time before `forward()` is invoked. It should have the following signature:  
>`hook(module, input) -> None`  

The hook should not modify the input.  
**Returns**:	a handle that can be used to remove the added hook by calling `handle.remove()`  
**Return type**:	torch.utils.hooks.RemovableHandle


***
#### register_buffer(name, tensor)
Adds a persistent buffer to the module.  
This is typically used to register a buffer that should not to be considered a model parameter. For example, BatchNorm’s running_mean is not a parameter, but is part of the persistent state.  
Buffers can be accessed as attributes using given names.  
***Parameters***:	
**name** (string) – name of the buffer. The buffer can be accessed from this module using the given name  
**tensor** (Tensor) – buffer to be registered.

>` self.register_buffer('running_mean', torch.zeros(num_features))`

***
#### register_parameter(name, param)
Adds a parameter to the module.  
The parameter can be accessed as an attribute using given name.  
***Parameters***:	  
**name** (string) – name of the parameter. The parameter can be accessed from this module using the given name  
**parameter** (Parameter) – parameter to be added to the module.   

***
#### state_dict(destination=None,prefix='',kepp_vars=False)  
Returns a dictionary containing a whole state of the module.  
Both parameters and persistent buffers(e.g. running averges) are included. Keys are corresponding parameter and buffer names.  
**Returns**: a dictionary containing a whole state of the module  
**Return type**: dict

In [25]:
module = nn.Linear(2,2)
module.state_dict().keys()

odict_keys(['weight', 'bias'])

####  to(*args,**kwargs)  
Moves and/or catsts the parameters and buffers.  
This can be called as  
>to(deviece=None, dtype=None, non_bolocking=False)


>to(dtype,non_blocking=False)


>to(tensor,non_blocking=False)

Its signature is similar to torch.Tensor.to(), but only accepts floating point desired dtype s. In addition, this method will only cast the floating point parameters and buffers to dtype (if given). The integral parameters and buffers will be moved device, if that is given, but with dtypes unchanged. When non_blocking is set, it tries to convert/move asynchronously with respect to the host if possible, e.g., moving CPU Tensors with pinned memory to CUDA devices.

***Parameters***:
**device**:torch.device the desired device of the paraeters asnd buffers in this module  
**dtype**: torch.dtype the desired floating point type of the floating point parameters and buffers in this module  
**tensor**: torch.Tensor Tensor whose dtype and device are the desired dtype and device for all parameters and buffers in this module  

**Returns**: self


In [28]:
import torch
linear = nn.Linear(2,2)
linear.weight

Parameter containing:
tensor([[-0.2885, -0.3279],
        [-0.1780,  0.5448]], requires_grad=True)

In [29]:
linear.to(torch.double)

Linear(in_features=2, out_features=2, bias=True)

In [30]:
linear.weight

Parameter containing:
tensor([[-0.2885, -0.3279],
        [-0.1780,  0.5448]], dtype=torch.float64, requires_grad=True)

In [31]:
gpu1 = torch.device("cuda:1")
linear.to(gpu1,dtype=torch.half,non_blocking=True)

Linear(in_features=2, out_features=2, bias=True)

In [32]:
linear.weight

Parameter containing:
tensor([[-0.2886, -0.3279],
        [-0.1780,  0.5449]],
       device='cuda:1', dtype=torch.float16, requires_grad=True)

In [33]:
cpu = torch.device("cpu")

In [34]:
linear.to(cpu)

Linear(in_features=2, out_features=2, bias=True)

In [35]:
linear.weight

Parameter containing:
tensor([[-0.2886, -0.3279],
        [-0.1780,  0.5449]], dtype=torch.float16, requires_grad=True)

#### train(mode=True)
Sets the module in training mode.  
This has any effect only on certian modules.
**Retuens**: self
**Return type**: Module

#### type(dst_type)
Casts all parameters and buffers to dst_type>
***Parameters***: **dst_type**: (type or string)
**Returns**: self  
**Return type**: Module


### zero_grad()
Sets gradients of all model parameters to zero.