# Torch 
###### version:0.4.0

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import numpy as np

### torh.numel

In [4]:
a = torch.randn(1,2,3,4,5)
torch.numel(a)

120

In [5]:
a = torch.zeros(4,4)
torch.numel(a)

16

### toch.tensor

In [6]:
torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [8]:
torch.tensor([[0.1111,0.22222,0.33333]],dtype=torch.float64,device=torch.device('cpu:0'))

tensor([[0.1111, 0.2222, 0.3333]], dtype=torch.float64)

In [9]:
torch.tensor(123.23)

tensor(123.2300)

In [10]:
torch.tensor([])

tensor([])

### torch.sparse_coo_tensor

In [13]:
i = torch.LongTensor([[0,1,1],[2,0,2]])
v = torch.FloatTensor([3,4,5])
torch.sparse_coo_tensor(i,v,torch.Size([2,4]))

torch.sparse.FloatTensor of size (2,4) with indices:
tensor([[0, 1, 1],
        [2, 0, 2]])
and values:
tensor([3., 4., 5.])

### toch.as_tensor(data,dtype=None,device=None)

In [14]:
a = np.array([1,2,3])
t = torch.as_tensor(a)

In [15]:
t

tensor([1, 2, 3])

In [16]:
t[0]

tensor(1)

In [17]:
t[0]=-1

In [18]:
t

tensor([-1,  2,  3])

### torch.from_numpy

In [19]:
a = np.array([1,2,3])
t = torch.from_numpy(a)

In [20]:
t

tensor([1, 2, 3])

In [21]:
t[0] = -1

In [22]:
t

tensor([-1,  2,  3])

### torch.zeros()

In [23]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [24]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

### torch.zeros_like

In [27]:
input = torch.empty(2,3)
torch.zeros_like(input)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### torch.ones()

In [28]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

### torch.ones_like()

In [30]:
input = torch.empty(2,3)
torch.ones_like(input)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### torch.arange(start=0, end, step=1)

In [31]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [32]:
torch.arange(1,4)

tensor([1, 2, 3])

In [33]:
torch.arange(1,2.5,0.5)

tensor([1.0000, 1.5000, 2.0000])

### torch.range(start=0, end, step=1)

In [34]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [35]:
torch.range(1,4)

/home/wangya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([1., 2., 3., 4.])

In [36]:
torch.range(1,2.5,0.5)

/home/wangya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([1.0000, 1.5000, 2.0000, 2.5000])

### torch.linspace(start,end,steps=100)

In [38]:
torch.linspace(2,10,steps=5)

tensor([ 2.,  4.,  6.,  8., 10.])

In [39]:
torch.linspace(-10,10,steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

### torch.logspace(start, end, steps=100)

In [40]:
torch.logspace(start=-10,end=10,steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [41]:
torch.logspace(start=0.1, end=1.0, steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

### torch.eye(n,m=None)

In [42]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [43]:
torch.eye(3,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

### torch.empty

In [44]:
torch.empty(2,3)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

### torch.empty_like()

In [46]:
input = torch.eye(3,2)
torch.empty_like(input)

tensor([[6.6135e-33, 4.5839e-41],
        [6.6135e-33, 4.5839e-41],
        [6.6136e-33, 4.5839e-41]])

In [47]:
input.new(input.size())

tensor([[0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000]])

### torch.full(size,fill_value)

In [48]:
torch.full((2,3),123.12)

tensor([[123.1200, 123.1200, 123.1200],
        [123.1200, 123.1200, 123.1200]])

In [50]:
torch.full((2,),1)

tensor([1., 1.])

### torch.full_like(input,fill_value)

In [51]:
input = torch.eye(3,2)
torch.full_like(input,3)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

### torch.cat

In [53]:
x = torch.randn(2,3)

In [54]:
x

tensor([[ 2.5733, -1.4863,  1.3077],
        [ 0.8679,  1.5882, -1.0902]])

In [55]:
torch.cat((x,x,x),0)

tensor([[ 2.5733, -1.4863,  1.3077],
        [ 0.8679,  1.5882, -1.0902],
        [ 2.5733, -1.4863,  1.3077],
        [ 0.8679,  1.5882, -1.0902],
        [ 2.5733, -1.4863,  1.3077],
        [ 0.8679,  1.5882, -1.0902]])

In [56]:
torch.cat((x,x,x),1)

tensor([[ 2.5733, -1.4863,  1.3077,  2.5733, -1.4863,  1.3077,  2.5733, -1.4863,
          1.3077],
        [ 0.8679,  1.5882, -1.0902,  0.8679,  1.5882, -1.0902,  0.8679,  1.5882,
         -1.0902]])

### torch.chunk(tensor,chunks,dim=0)

In [58]:
x = torch.randn(2,3)

In [59]:
torch.chunk(x,2,0)

(tensor([[ 0.4309, -1.1298, -0.7500]]), tensor([[2.2059, 1.0991, 2.2510]]))

In [61]:
torch.chunk(x,3,1)

(tensor([[0.4309],
         [2.2059]]), tensor([[-1.1298],
         [ 1.0991]]), tensor([[-0.7500],
         [ 2.2510]]))

In [62]:
torch.chunk(x,3,2)

RuntimeError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### torch.gather(input,dim,index)

In [64]:
t = torch.tensor([[1,2],[3,4]])
torch.gather(t,1,torch.tensor([[0,0],[1,0]]))

tensor([[1, 1],
        [4, 3]])

### torch.index_select(input,dim,index)

In [65]:
x = torch.randn(3,4)

In [66]:
x

tensor([[ 0.4126,  0.7041, -1.2275,  0.2766],
        [-0.0634, -1.3420,  0.4124, -0.5771],
        [ 1.0284, -0.4162, -0.6098, -0.9982]])

In [67]:
indices = torch.tensor([0,2])

In [68]:
torch.index_select(x,0,indices)

tensor([[ 0.4126,  0.7041, -1.2275,  0.2766],
        [ 1.0284, -0.4162, -0.6098, -0.9982]])

In [69]:
torch.index_select(x,1,indices)

tensor([[ 0.4126, -1.2275],
        [-0.0634,  0.4124],
        [ 1.0284, -0.6098]])

### torch.masked_select(input,mask)

In [70]:
x = torch.randn(3,4)

In [71]:
x

tensor([[ 0.3890, -0.7863, -1.8030,  1.1853],
        [ 1.1462, -1.4788, -0.0486, -0.5161],
        [-0.4309, -0.5425,  0.3556,  2.5313]])

In [72]:
mask = x.ge(0.5)

In [73]:
mask

tensor([[0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 0, 0, 1]], dtype=torch.uint8)

In [74]:
torch.masked_select(x,mask)

tensor([1.1853, 1.1462, 2.5313])

### torch.nonzero(input)

In [75]:
torch.nonzero(torch.tensor([1,1,1,0,1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [76]:
torch.nonzero(torch.tensor([[0.6,0.0,0.0,0.0],
                            [0.0,0.4,0.0,0.0],
                            [0.0,0.0,1.2,0.0],
                            [0.0,0.0,0.0,-0.4]]))

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

### torch.reshape(input,shape)

In [77]:
a = torch.arange(4)

In [78]:
a

tensor([0, 1, 2, 3])

In [79]:
torch.reshape(a,(2,2))

tensor([[0, 1],
        [2, 3]])

In [81]:
b  = torch.tensor([[0,1],[2,3]])
torch.reshape(b,(-1,))

tensor([0, 1, 2, 3])

### torch.split(tensor,split_size_or_sections,dim=0)

In [83]:
x= torch.randn(3,4)

In [89]:
torch.split(x,(1,2),0)

(tensor([[-0.9127,  2.4493, -1.2571,  0.3386]]),
 tensor([[-0.3355,  1.6447, -1.6115,  0.8696],
         [-0.0410,  0.0077, -1.4494,  0.4406]]))

In [85]:
torch.split(x,2,1)

(tensor([[-0.9127,  2.4493],
         [-0.3355,  1.6447],
         [-0.0410,  0.0077]]), tensor([[-1.2571,  0.3386],
         [-1.6115,  0.8696],
         [-1.4494,  0.4406]]))

In [90]:
torch.split(x,1,0)

(tensor([[-0.9127,  2.4493, -1.2571,  0.3386]]),
 tensor([[-0.3355,  1.6447, -1.6115,  0.8696]]),
 tensor([[-0.0410,  0.0077, -1.4494,  0.4406]]))

In [91]:
torch.split(x,(1,2,1),1)

(tensor([[-0.9127],
         [-0.3355],
         [-0.0410]]), tensor([[ 2.4493, -1.2571],
         [ 1.6447, -1.6115],
         [ 0.0077, -1.4494]]), tensor([[0.3386],
         [0.8696],
         [0.4406]]))

### torch.squeeze(input,dim=None)

In [92]:
x = torch.zeros(2,1,2,1,2)

In [94]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [95]:
y = torch.squeeze(x)

In [97]:
y.size()

torch.Size([2, 2, 2])

In [100]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [101]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [102]:
y = torch.squeeze(x,3)
y.size()

torch.Size([2, 1, 2, 2])

### torch.stack(seq,dim=0)
Concatenates sequence of tensors along a new dimension.

All tensors need to be of the same size.

In [105]:
x = torch.randn((2,3))
y = torch.randn((2,3))

In [106]:
x

tensor([[ 0.3083,  1.7692, -0.7832],
        [ 1.5340,  0.6389, -1.0337]])

In [107]:
y

tensor([[ 0.8156,  0.3950,  0.5004],
        [-1.0522, -1.1340, -0.6418]])

In [108]:
torch.stack((x,y),0)

tensor([[[ 0.3083,  1.7692, -0.7832],
         [ 1.5340,  0.6389, -1.0337]],

        [[ 0.8156,  0.3950,  0.5004],
         [-1.0522, -1.1340, -0.6418]]])

In [109]:
torch.stack((x,y),1)

tensor([[[ 0.3083,  1.7692, -0.7832],
         [ 0.8156,  0.3950,  0.5004]],

        [[ 1.5340,  0.6389, -1.0337],
         [-1.0522, -1.1340, -0.6418]]])

### torch.t(input)  
transpose()

In [110]:
x = torch.randn(2,3)
x

tensor([[ 0.1845, -1.2185, -0.2017],
        [ 0.3833,  0.4812, -0.2102]])

In [111]:
torch.t(x)

tensor([[ 0.1845,  0.3833],
        [-1.2185,  0.4812],
        [-0.2017, -0.2102]])

### torch.take(input,indices)
Returns a new tensor with the elements of input at the given indices. The input tensor is treated as if it were viewed as a 1-D tensor. The result takes the same shape as the indices.

In [113]:
src = torch.tensor([[4,3,5],
                   [6,7,8]])
torch.take(src,torch.tensor([0,2,5]))

tensor([4, 5, 8])

### torch.transpose(input,dim0,dim1)

In [114]:
x = torch.randn(2,3)
x

tensor([[ 1.3536,  1.2466, -2.1570],
        [ 1.2665,  0.0069, -1.2971]])

In [115]:
torch.transpose(x,0,1)

tensor([[ 1.3536,  1.2665],
        [ 1.2466,  0.0069],
        [-2.1570, -1.2971]])

In [117]:
x =torch.randn(2,3,4)
x

tensor([[[ 0.6945,  0.2237,  2.0203, -0.7691],
         [-0.6313,  1.3419,  0.9882, -0.3840],
         [-0.3679,  0.0181,  0.5595,  0.5775]],

        [[ 0.4115, -1.1913,  0.5393,  0.9103],
         [-1.8142, -1.7283, -0.0003, -1.1444],
         [-2.0786, -0.0647,  0.1076,  0.4556]]])

In [118]:
x = torch.transpose(x,1,2)

In [119]:
x

tensor([[[ 0.6945, -0.6313, -0.3679],
         [ 0.2237,  1.3419,  0.0181],
         [ 2.0203,  0.9882,  0.5595],
         [-0.7691, -0.3840,  0.5775]],

        [[ 0.4115, -1.8142, -2.0786],
         [-1.1913, -1.7283, -0.0647],
         [ 0.5393, -0.0003,  0.1076],
         [ 0.9103, -1.1444,  0.4556]]])

### torch.unbind(tensor,dim=0)

In [121]:
torch.unbind(torch.tensor([[1,2,3],
                           [4,5,6],
                           [7,8,9]]))
                        

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

### torch.unsqueeze(input,dim)

In [122]:
x = torch.tensor([1,2,3,4])
torch.unsqueeze(x,0)

tensor([[1, 2, 3, 4]])

In [123]:
torch.unsqueeze(x,1)

tensor([[1],
        [2],
        [3],
        [4]])

### torch.where(condition,x,y)

In [124]:
x = torch.randn(3,2)
y = torch.ones(3,2)
x

tensor([[-0.3310,  0.2215],
        [-0.2615, -0.9070],
        [-2.3643, -1.2774]])

In [125]:
torch.where(x>0,x,y)

tensor([[1.0000, 0.2215],
        [1.0000, 1.0000],
        [1.0000, 1.0000]])

In [126]:
x

tensor([[-0.3310,  0.2215],
        [-0.2615, -0.9070],
        [-2.3643, -1.2774]])

In [127]:
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

### torch.manual_seed(seed)
### torch.initial_seed()
### torch.get_rng_state()
### torch.set_rng_state(new_state)
### torch.default_generator=< torch._C.Generator object>
----

###  torch.bernoulli(input)
 0 $\le$ input $\le$ 1

In [128]:
a = torch.empty(3,3).uniform_(0,1)
a

tensor([[0.6280, 0.1186, 0.2535],
        [0.1130, 0.4323, 0.4498],
        [0.9462, 0.4673, 0.7711]])

In [129]:
torch.bernoulli(a)

tensor([[1., 0., 0.],
        [0., 0., 0.],
        [1., 0., 1.]])

In [130]:
a = torch.ones(3,3)
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [132]:
a = torch.zeros(3,3)
torch.bernoulli(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### torch.multinomial(input,num_samples)

In [133]:
weights = torch.tensor([0,10,3,0],dtype=torch.float)

In [134]:
weights

tensor([ 0., 10.,  3.,  0.])

In [137]:
torch.multinomial(weights,4)

tensor([1, 2, 0, 0])

In [136]:
torch.multinomial(weights,4,replacement=True)

tensor([2, 2, 1, 1])

### torch.normal(mean,std)
**mean**: Tensor  the tensor of per-element means   
**std**： Tensor the tensor of per-element standard deviations

In [138]:
torch.normal(mean = torch.arange(1.,11.),std=torch.arange(1,0,-0.1))

tensor([-1.0153,  1.5004,  3.2798,  3.6556,  4.0170,  5.7192,  6.6958,  8.1695,
         8.9020, 10.0759])

### torch.normal(mean=0.0,std)  
**mean**: float,op   the mean for all distributions  
**std**: Tensor the tensor of per-element standard deviations

In [139]:
torch.normal(mean=0.5,std=torch.arange(1.,6.))

tensor([ 1.6705, -0.1642, -0.1333,  3.4864,  1.8889])

### torch.normal(mean,std=1.0)
**mean**: Tensor: Tensor the tensor of per-element means  
**std**: float,op   the standard deviation for all distributions

In [140]:
torch.normal(mean=torch.arange(1.,6.))

tensor([1.0834, 1.3065, 3.8332, 4.4612, 7.1583])

### torch.rand(*sizes,...)
out=None,dtype=None,layout =torch.stride,device=None,requires_grad = False)

In [141]:
torch.rand(4)

tensor([0.7637, 0.7590, 0.9064, 0.9790])

In [142]:
torch.rand(2,3)

tensor([[0.6133, 0.9654, 0.3574],
        [0.0755, 0.2169, 0.8903]])

### torch.rand_like(input)
 == torch.rand(input.size())

### torch.randint(low=0,high,size)

In [143]:
torch.randint(3,5,(3,))

tensor([4., 4., 4.])

In [144]:
torch.randint(10,(2,2))

tensor([[0., 6.],
        [5., 1.]])

In [145]:
torch.randint(3,10,(2,2))

tensor([[5., 3.],
        [5., 6.]])

### torch.randn(*sizes)
uniform mena=0 variance=1

In [146]:
torch.randn(4)

tensor([-0.7213, -0.2560,  1.1830, -0.6701])

In [147]:
torch.randn(2,3)

tensor([[-1.0332,  0.4126, -0.1681],
        [ 0.2873,  0.9506, -0.9996]])

### torch.randn_like(input)
== torch.randn(input.size())

### torch.randperm(n)
returns a Random permutation of intergers from 0 to n-1

In [150]:
torch.randperm(4)

tensor([1, 0, 3, 2])

## In-place random sampling
#### torch.Tensor.bernoulli_()
#### torch.Tensor.cauchy_()
#### torch.Tensor.exponebtoal_()
#### torch.Tensor.geometric_()
#### torch.Tensor.log_normal_()
#### torch.Tensor.random_()
#### torch.Tensor.uniform_()

## Serialization

### torch.save(obj,f)

In [4]:
# Save to file
x = torch.tensor([0,1,2,3,4])
torch.save(x,'tensor.pt')

In [6]:
import io
# Save to io.BytesIO buffer
buffer = io.BytesIO()
torch.save(x, buffer)

### torch.load(f,map_location=None)

In [8]:
torch.load('tensor.pt')

tensor([0, 1, 2, 3, 4])

In [9]:
##Load all tensors onto the CPU
torch.load('tensor.pt',map_location=torch.device('cpu'))

tensor([0, 1, 2, 3, 4])

In [11]:
# Load all tensor onto the CPU, using a function
torch.load('tensor.pt',map_location=lambda storage, loc : storage)

tensor([0, 1, 2, 3, 4])

In [12]:
#Load all tensors into GPU 1
torch.load('tensor.pt',map_location=lambda storage, loc: storage.cuda(1))

tensor([0, 1, 2, 3, 4], device='cuda:1')

In [14]:
# Map tensors from GPU 1 to GPU 0
torch.load('tensor.pt', map_location={"cuda:1":"cuda:0"})

tensor([0, 1, 2, 3, 4])

In [19]:
# Load tensor from io.BytesIO object
with open('tensor.pt','rb') as f:
    buffer = io.BytesIO(f.read())
torch.load(buffer)

tensor([0, 1, 2, 3, 4])

## Parallelism

### torch.get_num_threads()  => int
   Gets the number of OpenMP threads used for parallelzing CPU  operations  
### torch.set_num_threads(int)
   Sets the number of OpenMP threads used for parallelizing CPU operations

## Locally disabling gradient comptutation

### torch.no_grad()
### torch.enable_grad()
### torch.set_grad_enabled()

In [20]:
x = torch.zeros(1,requires_grad = True)
with torch.no_grad():
    y = x*2
y.requires_grad

False

In [22]:
is_train = False
with torch.set_grad_enabled(is_train):
    y = x*2
y.requires_grad

False

In [23]:
torch.enable_grad()
y = x*2
y.requires_grad

True

In [25]:
torch.set_grad_enabled(False)
y = x*2
y.requires_grad

False

In [26]:
torch.set_grad_enabled(True)
y = x*2
y.requires_grad

True

## Math operations
### Pointwise Ops
&nbsp;
### torch.abs(input) &rarr; Tensor

In [27]:
torch.abs(torch.tensor([-1,-2,3]))

tensor([1, 2, 3])

### torch.acos(input) &rarr; Tensor

In [28]:
a = torch.randn(4)
a

tensor([-0.4399, -1.1784, -1.0763,  0.7929])

In [29]:
torch.acos(a)

tensor([2.0262,    nan,    nan, 0.6553])

### torch.add(input,value) &rarr; Tensor 
**input**: Tensor  
**value**: number

In [30]:
a =torch.randn(4)
a

tensor([-0.1789,  0.3203,  0.0501, -0.1073])

In [31]:
torch.add(a,20)

tensor([19.8211, 20.3203, 20.0501, 19.8927])

### torch.add(input,value=1, other) &rarr; Tensor
**input**:Tensor  
**value**:number  
**other**: Tensor  
***the shapes of input and other must be broadcastable***

In [32]:
a = torch.randn(4)
a

tensor([1.2532, 0.6762, 1.0532, 0.1568])

In [34]:
b = torch.randn(4,1)
b

tensor([[2.5785],
        [1.1788],
        [0.8098],
        [0.0287]])

In [35]:
torch.add(a,10,b)

tensor([[27.0379, 26.4610, 26.8380, 25.9415],
        [13.0416, 12.4647, 12.8417, 11.9453],
        [ 9.3511,  8.7742,  9.1512,  8.2548],
        [ 1.5398,  0.9628,  1.3398,  0.4434]])

### torch.addcdiv(input,value=1,tensor1,tensor2) &rarr; Tensor
>Parameters:	  
tensor (Tensor) – the tensor to be added  
value (Number, optional) – multiplier for tensor1./tensor2  
tensor1 (Tensor) – the numerator tensor  
tensor2 (Tensor) – the denominator tensor  
out (Tensor, optional) – the output tensor  

\begin{equation}
out_i = tensor_i + value \times  \frac{tensor1_i}{tensor2_i}
\end{equation}

***The shapes of tensor, tensor1, and tensor2 must be broadcastable.***

In [37]:
t = torch.randn(1,3)
t1 = torch.randn(3,1)
t2 = torch.randn(1,3)
t

tensor([[-0.2717, -0.5175, -0.7399]])

In [38]:
t1

tensor([[-0.6914],
        [ 0.5768],
        [ 2.2307]])

In [39]:
t2

tensor([[-0.4258,  0.3306, -0.8066]])

In [40]:
torch.addcdiv(t,0.1,t1,t2)

tensor([[-0.1093, -0.7266, -0.6542],
        [-0.4072, -0.3430, -0.8114],
        [-0.7956,  0.1573, -1.0165]])

### torch.addcmul(tensor,value=1,tensor1,tensor2) &rarr; Tensor
\begin{equation}
out_i = tensor_i + values \times tensor1_i \times tensor2_i
\end{equation}

In [41]:
t = torch.randn(1,3)
t1 = torch.randn(3,1)
t2 = torch.randn(1,3)
t

tensor([[-1.9432, -0.1277, -0.2151]])

In [42]:
t1

tensor([[ 0.3780],
        [-0.2364],
        [-0.5494]])

In [43]:
t2

tensor([[-0.6547, -0.3672, -0.2332]])

In [45]:
torch.addcmul(t,0.1,t1,t2)

tensor([[-1.9680, -0.1415, -0.2239],
        [-1.9278, -0.1190, -0.2096],
        [-1.9073, -0.1075, -0.2023]])

### torch.asin(input) &rarr; Tensor


In [46]:
a = torch.rand(4)
a

tensor([0.0001, 0.9039, 0.0954, 0.3600])

In [48]:
torch.asin(a)

tensor([8.8811e-05, 1.1287e+00, 9.5515e-02, 3.6831e-01])

### toch.atan(input) &rarr; Tensor

In [49]:
a = torch.randn(4)
a

tensor([ 0.2897, -0.2806,  0.4998, -0.6961])

In [50]:
torch.atan(a)

tensor([ 0.2820, -0.2736,  0.4634, -0.6081])

### torch.atan2(input1,input2) &rarr; Tensor

[atan2](https://baike.baidu.com/item/atan2/10931300)

In [51]:
a= torch.randn(4)
a

tensor([ 0.0724,  0.6360,  0.7506, -0.3745])

In [52]:
torch.atan2(a,torch.randn(4))

tensor([ 0.0352,  0.6895,  1.8478, -2.6591])

### torch.ceil(input) &rarr; Tensor
\begin{equation}
out_i =  \lceil input_i \rceil + 1
\end{equation}

In [53]:
a = torch.randn(4)
a

tensor([-0.1837, -1.0957,  0.6675,  0.6114])

In [54]:
torch.ceil(a)

tensor([-0., -1.,  1.,  1.])

### torch.clamp(input,min,max) &rarr Tensor  
\begin{equation}
  y_i=\begin{cases}
  min & if & x_i \le min\\
  x_i & if & min \le x_i \le max\\
  max & if & x_i \gt max
  \end{cases}
\end{equation}

![clamp](https://github.com/flyrae/pytorch_tutorial/blob/master/image/torch_clamp.JPG)
![clamp](./torch_clamp.jpg)

In [57]:
a = torch.randn(4)
a

tensor([-0.4222,  0.5512,  0.0724,  1.5514])

In [58]:
torch.clamp(a,min=-0.5,max=0.5)

tensor([-0.4222,  0.5000,  0.0724,  0.5000])

### torch.clamp(input,*,min) &rarr; Tensor
clamps all elements in input to be larger or equal min

In [60]:
a = torch.randn(4)
a

tensor([-1.4988,  1.5912,  1.2176, -0.6351])

In [62]:
torch.clamp(a,min=0.5)

tensor([0.5000, 1.5912, 1.2176, 0.5000])

### torch.clamp(input,*,max) &rarr; Tensor
clamps all elements in input to be smaller or equal min

In [63]:
a = torch.randn(4)
a

tensor([-0.4001, -0.8992, -0.8597,  2.6875])

In [64]:
torch.clamp(a,max=0.5)

tensor([-0.4001, -0.8992, -0.8597,  0.5000])

### torch.cos(input) &rarr; Tensor

In [67]:
a = torch.randn(4)
a

tensor([ 1.9235,  0.8009, -1.4073,  0.8892])

In [68]:
torch.cos(a)

tensor([-0.3455,  0.6960,  0.1628,  0.6300])

### torch.cosh(input) &rarr; Tensor
[cosh](https://baike.baidu.com/item/cosh/3535060):双曲余弦值
\begin{equation}
out_i = cosh(input_i)
\end{equation}

In [69]:
a = torch.randn(4)
a

tensor([-0.4519, -0.1469,  1.0229, -0.6896])

In [70]:
torch.cosh(a)

tensor([1.1038, 1.0108, 1.5704, 1.2474])

### torch.div(input,value)

In [71]:
a = torch.randn(5)
a

tensor([ 0.8557, -0.5693,  0.2530, -0.6201, -1.4699])

In [72]:
torch.div(a,0.5)

tensor([ 1.7113, -1.1387,  0.5059, -1.2402, -2.9398])

### torch.div(input,other) &rarr; Tensor
\begin{equation}
out_i = \dfrac{input_i} {other_i}
\end{equation}

In [74]:
a = torch.randn(4,4)
a

tensor([[ 0.3224,  0.3927,  1.2757,  0.2755],
        [ 1.0841, -0.1547, -1.5228, -0.6846],
        [-0.4330, -0.3775, -0.7314,  0.8024],
        [-0.7253,  1.1161, -0.6508, -1.4592]])

In [76]:
b = torch.randn(4,4)
b

tensor([[-1.8211,  0.3319, -1.3190,  0.5377],
        [ 0.8194, -0.7360,  1.1753, -0.4185],
        [ 0.6335, -0.0063, -1.5335,  0.8032],
        [ 0.1412,  0.7148,  0.7281, -0.3557]])

In [77]:
torch.div(a,b)

tensor([[-0.1770,  1.1831, -0.9671,  0.5124],
        [ 1.3230,  0.2102, -1.2956,  1.6359],
        [-0.6835, 59.9811,  0.4770,  0.9991],
        [-5.1363,  1.5613, -0.8938,  4.1022]])

### torch.erf(tensor) &rarr; Tensor
\begin{equation}
erf(x) = \frac{2}{\sqrt{\pi}} \int_0^x{e^{-t^2}}dt
\end{equation}

In [79]:
torch.erf(torch.tensor([0,-1.,10.]))

tensor([ 0.0000, -0.8427,  1.0000])

### torch.erfc(tensor) &rarr; Tensor
\begin{equation}
erfc(x) = 1-erf(x)
\end{equation}

In [81]:
torch.erfc(torch.tensor([0,-1.,10.]))

tensor([1.0000e+00, 1.8427e+00, 1.4013e-45])

### torvh.erfinv(tensor) &rarr; Tensor
Computes the inverse error function of each element. The inverse error function is defined in the range (−1,1) as:
\begin{equation}
erfinv(erf(x)) = x
\end{equation}

In [82]:
torch.erfinv(torch.tensor([0,0.5,-1.]))

tensor([0.0000, 0.4769,   -inf])

### torch.exp(tensor) &rarr; Tensor

In [84]:
import math
torch.exp(torch.tensor([0,math.log(2)]))

tensor([1., 2.])

### torch.expm1(tensor) &rarr; Tensor
 == torch.exp -1

In [85]:
import math
torch.expm1(torch.tensor([0,math.log(2)]))

tensor([0., 1.])

### torch.floor(input)
\begin{equation}
out_i = \lfloor input_i \rfloor
\end{equation}

In [86]:
a = torch.randn(4)
a

tensor([ 0.1830, -2.1857,  0.9747,  0.3545])

In [87]:
torch.floor(a)

tensor([ 0., -3.,  0.,  0.])

### torch.fmod(input,divisor) &rarr; Tensor
Computes the element-wise remainder of division.  
When divisor is a tensor, the shapes of input and divisor must be broadcastable.
Parameters:	 
**input** (Tensor) – the dividend  
**divisor** (Tensor or float) – the divisor, which may be either a number or a tensor of the same shape as the dividend  

In [89]:
torch.fmod(torch.tensor([-3.,-2.,-1.,1,2,3]),2)

tensor([-1., -0., -1.,  1.,  0.,  1.])

In [90]:
torch.fmod(torch.tensor([1.,2,3,4,5]),1.5)

tensor([1.0000, 0.5000, 0.0000, 1.0000, 0.5000])

### torch.frac(tensor) &rarr; Tensor
\begin{equation}
out_i = input_i - \lfloor input_i \rfloor
\end{equation}

In [91]:
torch.frac(torch.tensor([1,2.5,-3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

### torch.lerp(start,end,weight)
\begin{equation}
out_i = start_i + weight \times (end_i-start_i)
\end{equation}
**start**: tensor  
**end**: tensor  
**weight**:weight  

In [92]:
start = torch.arange(1.,5.)
end = torch.empty(4).fill_(10)
start

tensor([1., 2., 3., 4.])

In [93]:
end

tensor([10., 10., 10., 10.])

In [95]:
torch.lerp(start,end,0.5)

tensor([5.5000, 6.0000, 6.5000, 7.0000])

### torch.log(input) &rarr; Tensor  
\begin{equation}
y_i = \log_e(x_i)
\end{equation}
  
### torch.log10(input)
\begin{equation}
y_i = \log_{10}(x_i)
\end{equation}
  
   
### torch.log1p(input)
\begin{equation}
y_i = \log_e(x_i+1)
\end{equation}
  
 ### torch.log2(input)
 \begin{equation}
 y_i = \log_2(x_i)
\end{equation}

In [98]:
a = torch.randn(5)
a

tensor([-0.5929,  1.8605, -1.0025,  0.0423, -2.1968])

In [99]:
torch.log(a)

tensor([    nan,  0.6209,     nan, -3.1619,     nan])

### torch.mul(input,value)
\begin{equation}
out_i = value \times input_i
\end{equation}
  
 ### torch.mul(input,other)
 \begin{equation}
out_i = input_i \times other_i
\end{equation}

In [100]:
a = torch.randn(3)
a

tensor([ 0.8532,  0.0576, -0.3593])

In [101]:
torch.mul(a,100)

tensor([ 85.3192,   5.7634, -35.9288])

In [102]:
a = torch.rand(4,1)
a

tensor([[0.9120],
        [0.9704],
        [0.1582],
        [0.3307]])

In [103]:
b = torch.randn(1,4)
b

tensor([[ 2.2881,  2.0717, -1.1026,  0.3697]])

In [104]:
torch.mul(a,b)

tensor([[ 2.0867,  1.8893, -1.0055,  0.3371],
        [ 2.2204,  2.0104, -1.0700,  0.3587],
        [ 0.3621,  0.3278, -0.1745,  0.0585],
        [ 0.7566,  0.6850, -0.3646,  0.1222]])

###  torch.neg(input) &rarr; Tensor

In [105]:
a = torch.randn(5)
a

tensor([ 0.0753,  1.1620, -0.1606,  0.2549,  1.1231])

In [106]:
torch.neg(a)

tensor([-0.0753, -1.1620,  0.1606, -0.2549, -1.1231])

### torch.pow(input,exponent) &rarr; Tensor
**exponent**: scalar or tensor
\begin{equation}
out_i = x_i^{exponent}
\end{equation}

or  

\begin{equation}
out_i = x_i^{exponent_i}
\end{equation}

In [107]:
a = torch.randn(4)
a

tensor([-0.2805,  0.4555, -1.2507,  1.6525])

In [109]:
torch.pow(a,2)

tensor([0.0787, 0.2075, 1.5643, 2.7306])

In [110]:
a = torch.arange(1.,5.)
a

tensor([1., 2., 3., 4.])

In [111]:
exp = torch.arange(1.,5.)
exp

tensor([1., 2., 3., 4.])

In [112]:
torch.pow(a,exp)

tensor([  1.,   4.,  27., 256.])

### torch.pow(base,input) &rarr; Tensor
**base**: scalar float
**input**:tensor
\begin{equation}
out_i = base^{input_i}
\end{equation}

In [113]:
exp = torch.arange(1.,5.)
base = 2
torch.pow(base,exp)

tensor([ 2.,  4.,  8., 16.])

### torch.reciprocal(input) &rarr; Tensor
\begin{equation}
out_i = \frac{1} {input_i}
\end{equation}

In [114]:
a = torch.randn(4)
a

tensor([-0.4327,  1.0272,  0.0258,  0.0200])

In [115]:
torch.reciprocal(a)

tensor([-2.3110,  0.9735, 38.7571, 50.1244])

### torch.remainder(input,divisor) &rarr; Tensor
**input**: tensor  
**divisor**:tensor or float

In [117]:
torch.remainder(torch.tensor([-3.,-2.,-1,1,2,3]),2)

tensor([1., 0., 1., 1., 0., 1.])

In [3]:
torch.remainder(torch.tensor([1.,2,3,4,5]),1.5)

tensor([1.0000, 0.5000, 0.0000, 1.0000, 0.5000])

### torch.round(input)

In [4]:
a = torch.randn(4)
a

tensor([-0.4964,  0.3275,  0.4434, -1.2002])

In [5]:
torch.round(a)

tensor([-0.,  0.,  0., -1.])

### torch.rsqrt(input) 

\begin{equation}
out_i = \frac{1} {\sqrt{input_i}}
\end{equation}

In [6]:
a = torch.randn(4)
a

tensor([-0.0223, -2.3061, -0.0100,  0.0485])

In [7]:
torch.rsqrt(a)

tensor([   nan,    nan,    nan, 4.5404])

### torch.sigmoid(input) &rarr; Tensor
\begin{equation}
out_i = \frac{1} {1+ e^{-input_i}}
\end{equation}

In [8]:
a = torch.randn(4)
a

tensor([ 0.6860, -1.3042,  0.0199, -2.0714])

In [9]:
torch.sigmoid(a)

tensor([0.6651, 0.2135, 0.5050, 0.1119])

### torch.sign(input)

In [11]:
a = torch.randn(4)
a

tensor([-0.3767,  0.2964, -0.6505, -0.4146])

In [12]:
torch.sign(a)

tensor([-1.,  1., -1., -1.])

### torch.sin(input)

In [13]:
a =torch.randn(4)
a

tensor([ 0.2873,  0.3989,  1.2979, -1.1278])

In [14]:
torch.sin(a)

tensor([ 0.2834,  0.3884,  0.9630, -0.9035])

### torch.sqrt(input)
\begin{equation}
out_i = \sqrt{input_i}
\end{equation}

In [15]:
a = torch.randn(4)
a

tensor([ 0.1832,  0.0505, -2.0238,  0.9677])

In [16]:
torch.sqrt(a)

tensor([0.4280, 0.2247,    nan, 0.9837])

### torch.tan(input)
\begin{equation}
out_i = tan(input_i)
\end{equation}

In [17]:
a = torch.randn(4)
a

tensor([ 0.2481, -0.1235, -0.0770,  1.2690])

In [18]:
torch.tan(a)

tensor([ 0.2533, -0.1242, -0.0771,  3.2126])

### torch.tanh(input)

\begin{equation}
out_i = tanh(input_i)
\end{equation}

In [19]:
a = torch.randn(4)
a

tensor([-0.3647,  0.6298,  1.1132, -0.3679])

In [20]:
torch.tanh(a)

tensor([-0.3494,  0.5579,  0.8052, -0.3522])

### torch.trunc(input)
Returns a new tensor with the truncated integer values of the elements of input.

In [21]:
a = torch.randn(4)
a

tensor([-0.1673,  1.5777,  0.2335, -0.5940])

In [22]:
torch.trunc(a)

tensor([-0.,  1.,  0., -0.])

## Reduction Ops
### torch.argmax(input,dim=None,keepdim=False)
Returns the indices of the maximum values of a tensor across a dimension.  

In [23]:
a = torch.randn(4,4)
a

tensor([[ 0.0497, -0.2894,  1.7671,  0.1857],
        [ 0.7913, -1.2123, -0.1896, -0.0994],
        [-0.6568, -0.5906,  1.1089,  0.2628],
        [ 1.4260,  1.4894,  1.0176,  1.8022]])

In [24]:
torch.argmax(a,dim=1)

tensor([2, 0, 2, 3])

### torch.argmin(input,dim=None,keppdim=False)
sth. like argmax

In [25]:
a = torch.randn(4,4)
a

tensor([[-2.1532, -1.7278, -1.3255, -0.4668],
        [-0.1158,  0.9673, -0.6377, -0.5966],
        [ 0.2792, -0.1625, -0.4034, -0.1479],
        [-0.1362, -0.7595, -0.2426, -0.5096]])

In [26]:
torch.argmin(a,dim=1)

tensor([0, 2, 2, 1])

### torch.cumprod(input,dim,dtype=None)
Returns the cumulative product of elements of input in the dimension dim.  
\begin{equation}
y_i = x_1 \times x_2 \times x_3 \times \cdots \times x_i
\end{equation}

In [27]:
a = torch.randn(10)
a

tensor([ 1.4592,  0.3755, -0.6952, -0.6394, -1.1005,  1.1080,  0.4343,  0.9313,
         0.3582, -0.5671])

In [28]:
torch.cumprod(a,dim=0)

tensor([ 1.4592,  0.5479, -0.3809,  0.2435, -0.2680, -0.2970, -0.1290, -0.1201,
        -0.0430,  0.0244])

In [29]:
a[5] =0

In [30]:
torch.cumprod(a,dim=0)

tensor([ 1.4592,  0.5479, -0.3809,  0.2435, -0.2680, -0.0000, -0.0000, -0.0000,
        -0.0000,  0.0000])

### torch.sumsum(input,dim)
Returns the cumulative sum of elements of input in the dimension dim.  
\begin{equation}
y_i = x_1 + x_2 + x_3 + \cdots + x_i
\end{equation}

In [31]:
a = torch.randn(10)
a

tensor([ 0.5069,  0.4284,  1.4547, -1.6327,  0.7725,  0.1315, -0.5064,  0.9074,
        -0.1084,  0.0273])

In [34]:
torch.cumsum(a,dim=0)

tensor([0.5069, 0.9353, 2.3899, 0.7572, 1.5297, 1.6611, 1.1547, 2.0621, 1.9537,
        1.9809])

### torch.dist(input,other,p = 2)
Returns the p-norm of (input-other)
The shapes of input and other must be broadcastable.  
**input**: Tensor
**other**: Tensor ( the Right-hand-side input tesnsor)
**p**: float

In [36]:
x = torch.randn(4)
x

tensor([ 0.1049,  1.7078, -0.5606,  1.2349])

In [37]:
y = torch.randn(4)
y

tensor([1.4127, 0.4591, 0.0043, 0.2851])

In [39]:
z = torch.randn(4,4)
z

tensor([[ 0.2670, -0.6342, -1.0125, -1.0300],
        [-2.1413,  0.1245,  0.4322, -0.2926],
        [-0.9039,  0.7834, -0.7433, -0.4721],
        [ 2.2795,  0.2441,  0.6519, -0.4096]])

In [41]:
torch.dist(x,y,3.5)

tensor(1.6446)

In [42]:
torch.dist(x,y,3)

tensor(1.7348)

In [43]:
torch.dist(x,y)

tensor(2.1192)

In [44]:
torch.dist(x,y,0)

tensor(inf)

In [45]:
torch.dist(x,y,1)

tensor(4.0712)

In [46]:
torch.dist(x,z,1)

tensor(21.8889)

### torch.logsumexp(input,dim,keepdim=False)
Returns the log of summed exponentials of each row of the input tensor in the given dimension dim. The computation is numerically stabilized.  
\begin{equation}
logsumexp(x)_i = log \sum_j exp(x_{i,j})
\end{equation}

**input**:tensor  
**dim**:int or tuple of python : ints

In [47]:
a = torch.randn(3,3)
torch.logsumexp(a,1)

tensor([1.7749, 1.7612, 1.3092])

### torch.mean(input)

### torch.mean(input,dim,keep_dim=False)


In [48]:
a = torch.rand(1,3)
a

tensor([[0.2126, 0.2194, 0.9765]])

In [49]:
torch.mean(a)

tensor(0.4695)

In [50]:
a = torch.randn(4,4)
a

tensor([[-0.0925,  2.0189,  0.8256, -1.2649],
        [ 1.2222, -0.3972, -0.3707, -0.1473],
        [ 0.5263,  0.5659, -2.0225,  0.1891],
        [-0.8276,  0.1966,  1.5602,  0.9839]])

In [51]:
torch.mean(a,1)

tensor([ 0.3718,  0.0768, -0.1853,  0.4783])

In [53]:
torch.mean(a,1,keepdim=True)

tensor([[ 0.3718],
        [ 0.0768],
        [-0.1853],
        [ 0.4783]])

### torch.median(input)

### torch.median(input,dim=-1,keepdim=False,values=None,indices=None) &rarr; (Tensor,LongTensor)
Returns the median value of each row of the input tensor in the given dimension dim. Also returns the index location of the median value as a LongTensor.

In [54]:
a = torch.randn(1,3)
a

tensor([[ 0.7668,  1.1191, -0.5563]])

In [55]:
torch.median(a)

tensor(0.7668)

In [56]:
a = torch.randn(4,5)
a

tensor([[-0.0730,  0.8085,  0.3448,  0.2891, -0.0152],
        [ 0.5968, -1.4491, -0.6510, -0.5086,  0.1395],
        [-0.0339, -0.7931,  0.3621,  0.7848, -0.2274],
        [ 1.4834,  1.7174,  0.7993, -1.0887, -1.3751]])

In [57]:
torch.median(a,1)

(tensor([ 0.2891, -0.5086, -0.0339,  0.7993]), tensor([3, 3, 0, 2]))

### torch.mode(input,dim=-1,keepdim=False,values=None,indices=None)  &rarr;(Tensor,LongTensor)
mode:众数  
Returns the mode value of each row of the input tensor in the given dimension dim. Also returns the index location of the mode value as a LongTensor.

By default, dim is the last dimension of the input tensor.

In [58]:
a = torch.randn(4,5)
a

tensor([[ 0.9848, -0.9843, -0.6722, -0.3354,  0.5399],
        [-0.1036, -1.4843,  0.5884, -0.5414,  1.5096],
        [ 0.1141,  0.2389,  0.1236, -1.5882,  0.5818],
        [-0.9514, -1.2901,  0.0891,  0.1376, -0.9407]])

In [60]:
torch.mode(a)

(tensor([-0.9843, -1.4843, -1.5882, -1.2901]), tensor([1, 1, 3, 1]))

### torch.norm(input,p=2)

\begin{equation}
\parallel x \parallel_p = \sqrt[p]{x_1^p +x_2^p+ \cdots + x_N^p}
\end{equation}

In [61]:
a = torch.randn(1,3)
a

tensor([[0.1245, 0.7997, 0.9312]])

In [62]:
torch.norm(a,3)

tensor(1.0971)

### torch.norm(input,p,dim,keepdim=False) &rarr Tensor
Returns the p-norm of each row of the input tensor in the given dimension dim.

In [63]:
a = torch.randn(4,2)
a

tensor([[-1.0832, -2.2626],
        [-0.2929, -1.5025],
        [-0.6977,  0.1839],
        [-0.9940, -1.0722]])

In [64]:
torch.norm(a,2,1)

tensor([2.5085, 1.5308, 0.7216, 1.4621])

In [65]:
torch.norm(a,0,1,True)

tensor([[2.],
        [2.],
        [2.],
        [2.]])

### torch.prod(input) &rarr Tensor
Returns the product of all elements in the input tensor

In [66]:
a = torch.randn(1,3)
a

tensor([[ 0.6691, -1.0513,  0.8620]])

In [67]:
torch.prod(a)

tensor(-0.6064)

### torch.prod(input,dim,keepdim=False) &rarr Tensor
Returns the product of each row of the input tensor in the given dimension dim.

In [68]:
a = torch.randn(4,2)
a

tensor([[ 0.1134, -0.7377],
        [-0.2178, -0.2545],
        [-1.2420, -0.3113],
        [-0.5668, -1.0963]])

In [69]:
torch.prod(a,1)

tensor([-0.0836,  0.0554,  0.3866,  0.6213])

### torch.std(input,unbiased = True)
Returns the standard-deviation of all elements in the input tensor.  
  
### torch.std(input,dim,keppdim=False,unbiased=True)
Returns the standard-deviation of each row of the input tensor in the given dimension dim.

In [70]:
a = torch.randn(4,4)

In [71]:
torch.std(a)

tensor(0.9314)

In [72]:
torch.std(a,dim=1)

tensor([0.8612, 0.4752, 1.1845, 0.4412])

### torch.sum(input,dtype=None)
Returns the sum of all elements in the input tensor.  
### torch.sum(input,dim,keepdim=False,dtype=None)
Returns the sum of each row of the input tensor in the given dimension dim. If :attr::dim is a list of dimensions, reduce over all of them.

In [73]:
a = torch.randn(4,4)
a

tensor([[ 0.1768,  1.2521, -1.0661,  1.0899],
        [-0.8745, -0.0520,  0.1529, -0.5867],
        [ 0.1110, -0.7021,  1.3278,  1.3999],
        [-0.0619,  0.7525,  0.6036, -0.5650]])

In [74]:
torch.sum(a)

tensor(2.9580)

In [75]:
b = torch.arange(4*5*6).view(4,5,6)
b

tensor([[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]])

In [76]:
torch.sum(b,(2,1))

tensor([ 435, 1335, 2235, 3135])

In [86]:
torch.sum(torch.sum(b,dim=2),dim=1)

tensor([ 435, 1335, 2235, 3135])

### torch.unqiue(input,sorted=False,return_inerse=False）
Returns the unique scalar elements of the input tensor as a 1-D tensor.  
Returns:  	
A tensor or a tuple of tensors containing

&nbsp;&nbsp;**output (Tensor)**: the output list of unique scalar elements.  
&nbsp;&nbsp;**inverse_indices (Tensor)**: (optional) if return_inverse is True, there will be a 2nd returned tensor (same shape as input) representing the indices for where elements in the original input map to in the output; otherwise, this function will only return a single tensor.

In [89]:
a = torch.tensor([1,3,2,3],dtype=torch.long)

In [91]:
torch.unique(a)

tensor([2, 3, 1])

In [92]:
output,inverse_indices = torch.unique(a,sorted=True,return_inverse=True)

In [93]:
output

tensor([1, 2, 3])

In [94]:
inverse_indices

tensor([0, 2, 1, 2])

In [95]:
b = torch.tensor([[1,3],[2,3]],dtype=torch.long)
output,inverse_indices = torch.unique(b,sorted=True,return_inverse=True)

In [96]:
output

tensor([1, 2, 3])

In [97]:
inverse_indices

tensor([[0, 2],
        [1, 2]])

### torch.var(input,unbiased=True) &rarr Tensor
Returns the variance of all elements in the input tensor.  
### torch.var(input,dim,keepdim=False,unbiased=True) &rarr Tensor
Returns the variance of each row of the input tensor in the given dimension dim.

In [98]:
a = torch.randn(4,4)
a

tensor([[ 0.7010,  0.6726, -0.4067,  0.1985],
        [ 0.7359,  0.3816, -0.5946,  0.0422],
        [ 0.8214, -0.0906,  0.1476,  0.4434],
        [ 1.4222, -1.0913, -0.8624,  0.4576]])

In [99]:
torch.var(a,1)

tensor([0.2697, 0.3209, 0.1548, 1.3885])

In [100]:
torch.var(a)

tensor(0.4470)

## Comparison Ops
### torch.eq(input,other)
Computes element-wise equality
**input**: Tensor  
**other**: Tensor or float  
**Returns**: A torch.ByteTensor containing a 1 at each location where comparison is true


### torch.ge(input,other)
Computes input≥other element-wise.  
### torch.gt(input,other)
Computes input>other element-wise.  


### torch.le(input,other)
Computes input≤other element-wise.  
### torch.lt(input,other)
Computes input <other element-wise. 

In [101]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[1,1],[4,4]])

In [102]:
torch.eq(a,b)

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

## torch.equal(tensor1,tensor2) &rarr; bool
True if two tensors have the same size and elements, False otherwise.

In [107]:
torch.equal(torch.Tensor([1,2]),torch.Tensor([1,2]))

True

### torch.isfinite(tensor)
Returns a new tensor with boolean elements representing if each element is Finite or not.

### torch.isinf(tensor)
Returns a new tensor with boolean elements representing if each element is +/-INF or not.

### torch.isnan(tensor)
Returns a new tensor with boolean elements representing if each element is NaN or not.

In [108]:
torch.isfinite(torch.Tensor([1,float('inf'),2,float('inf'),float('nan')]))

tensor([1, 0, 1, 0, 0], dtype=torch.uint8)

In [109]:
torch.isinf(torch.Tensor([1,float('inf'),2,float('inf'),float('nan')]))

tensor([0, 1, 0, 1, 0], dtype=torch.uint8)

In [110]:
torch.isnan(torch.Tensor([1,float('inf'),2,float('inf'),float('nan')]))

tensor([0, 0, 0, 0, 1], dtype=torch.uint8)

### torch.kthvalue(input,k,dim=None,keepdim = False) &rarr; (Tensor,LongTensor)
Returns the k th smallest element of the given input tensor along a given dimension.  
If dim is not given, the last dimension of the input is chosen.  
A tuple of (values, indices) is returned, where the indices is the indices of the kth-smallest element in the original input tensor in dimension dim.  

In [111]:
x = torch.arange(1.,6.)
x

tensor([1., 2., 3., 4., 5.])

In [112]:
torch.kthvalue(x,4)

(tensor(4.), tensor(3))

In [113]:
x = torch.arange(1.,7.).resize_(2,3)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [114]:
torch.kthvalue(x,2,0,True)

(tensor([[4., 5., 6.]]), tensor([[1, 1, 1]]))

### torch.max(input) &rarr; Tensor
Returns the maximum value of all elements in the input tensor.
### torch.max(input,dim,keppdim=False) &rarr; (Tensor,LongTensor)
Returns the maximum value of each row of the input tensor in the given dimension dim. The second return value is the index location of each maximum value found (argmax).  

In [116]:
a = torch.randn(4,4)
a

tensor([[-0.7705, -0.7355, -0.2868,  0.7561],
        [-0.5960, -0.1235, -2.6040,  0.8603],
        [ 0.0252,  2.5719,  0.9136,  0.5260],
        [ 0.5143,  1.2222,  0.0810, -0.7546]])

In [117]:
torch.max(a,1)

(tensor([0.7561, 0.8603, 2.5719, 1.2222]), tensor([3, 3, 1, 1]))

### torch.max(input,other)
\begin{equation}
out_i = max(tensor_i,other_i)
\end{equation}

In [118]:
a = torch.randn(4)
a

tensor([-0.0021, -0.0152,  0.4442,  0.7071])

In [119]:
b = torch.randn(4)
b

tensor([ 0.6576, -1.0906, -1.3773, -0.0392])

In [120]:
torch.max(a,b)

tensor([ 0.6576, -0.0152,  0.4442,  0.7071])

###  torch.min(input)

### torch.min(input,dim,keepdim=False,out=None) &rarr; (Tensor,LongTensor)


### torch.min(input,other)

### torch.ne(input,other) &rarr; Tensor
Computes \begin{equation} input \ne other\end{equation} element-wise

In [121]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[1,1],[4,4]])
torch.ne(a,b)

tensor([[0, 1],
        [1, 0]], dtype=torch.uint8)

### torch.sort(input,dim=None,descending=False)&rarr;(Tensor,LongTensor)
Sorts the elements of the input tensor along a given dimension in ascending order by value.  

If dim is not given, the last dimension of the input is chosen.  

If descending is True then the elements are sorted in descending order by value.  

A tuple of (sorted_tensor, sorted_indices) is returned, where the sorted_indices are the indices of the elements in the original input tensor.

In [123]:
x = torch.randn(3,4)
x

tensor([[ 0.7576,  0.6047, -1.1833,  1.1726],
        [-0.7300,  2.3320,  0.2237, -1.3353],
        [ 1.1686, -2.2563,  0.8601,  0.1372]])

In [124]:
sorted,indices = torch.sort(x)

In [125]:
sorted

tensor([[-1.1833,  0.6047,  0.7576,  1.1726],
        [-1.3353, -0.7300,  0.2237,  2.3320],
        [-2.2563,  0.1372,  0.8601,  1.1686]])

In [126]:
indices

tensor([[2, 1, 0, 3],
        [3, 0, 2, 1],
        [1, 3, 2, 0]])

In [127]:
sorted,indices = torch.sort(x,0)

In [128]:
sorted

tensor([[-0.7300, -2.2563, -1.1833, -1.3353],
        [ 0.7576,  0.6047,  0.2237,  0.1372],
        [ 1.1686,  2.3320,  0.8601,  1.1726]])

In [129]:
indices

tensor([[1, 2, 0, 1],
        [0, 0, 1, 2],
        [2, 1, 2, 0]])

### torch.topk(input,k,dim=None,largest=True,sorted=True) &rarr;(Tensor,LongTensor)
Returns the k largest elements of the given input tensor along a given dimension.  

If dim is not given, the last dimension of the input is chosen.  

If largest is False then the k smallest elements are returned.  

A tuple of (values, indices) is returned, where the indices are the indices of the elements in the original input tensor.  

The boolean option sorted if True, will make sure that the returned k elements are themselves sorted

In [130]:
x = torch.arange(1.,6.)
x

tensor([1., 2., 3., 4., 5.])

In [131]:
torch.topk(x,3)

(tensor([5., 4., 3.]), tensor([4, 3, 2]))